const seoKeywords = [
    "APK", "alkohol per krona", "Systembolaget", "alkohol", "drycker", "billig alkohol", 
    "bästa alkohol", "hög APK", "Systembolaget APK", "alkohol prisvärd", "alkohol ranking", 
    "högst mängd alkohol per krona", "prisvärd alkohol", "billigaste alkohol", 
    "bästa alkohol på Systembolaget", "hög APK Systembolaget", "mest alkohol för pengarna", 
    "prisvärd alkohol Systembolaget", "billig alkohol Systembolaget", "bästa alkohol Systembolaget", 
    "hög APK Systembolaget", "mest prisvärd alkohol", "billigaste alkohol", "bästa alkohol", 
    "hög APK", "mest prisvärd alkohol per krona", "billigaste alkohol per krona", 
    "bästa alkohol per krona", "hög APK per krona", "Systembolaget bästa köp", 
    "Systembolaget billigaste alkohol", "Systembolaget hög APK", "Systembolaget mest prisvärd", 
    "Systembolaget alkohol ranking", "Systembolaget alkohol prisvärd", "Systembolaget alkohol billig", 
    "Systembolaget alkohol bäst", "Systembolaget alkohol hög APK", "Systembolaget alkohol mest prisvärd", 
    "Systembolaget alkohol billigast", "Systembolaget alkohol bäst", "Systembolaget alkohol hög APK", 
    "mest alkohol för pengarna Systembolaget", "mest prisvärd alkohol Systembolaget", 
    "billigaste alkohol Systembolaget", "bästa alkohol Systembolaget", "hög APK Systembolaget", 
    "mest prisvärd alkohol per krona Systembolaget", "billigaste alkohol per krona Systembolaget", 
    "bästa alkohol per krona Systembolaget", "hög APK per krona Systembolaget", 
    "Systembolaget bästa köp", "Systembolaget billigaste alkohol", "Systembolaget hög APK", 
    "Systembolaget mest prisvärd", "Systembolaget alkohol ranking", "Systembolaget alkohol prisvärd", 
    "Systembolaget alkohol billig", "Systembolaget alkohol bäst", "Systembolaget alkohol hög APK", 
    "Systembolaget alkohol mest prisvärd", "Systembolaget alkohol billigast", "Systembolaget alkohol bäst", 
    "Systembolaget alkohol hög APK", "mest alkohol för pengarna Systembolaget", 
    "mest prisvärd alkohol Systembolaget", "billigaste alkohol Systembolaget", 
    "bästa alkohol Systembolaget", "hög APK Systembolaget", "mest prisvärd alkohol per krona Systembolaget", 
    "billigaste alkohol per krona Systembolaget", "bästa alkohol per krona Systembolaget", 
    "hög APK per krona Systembolaget", "Systembolaget bästa köp", "Systembolaget billigaste alkohol", 
    "Systembolaget hög APK", "Systembolaget mest prisvärd", "Systembolaget alkohol ranking", 
    "Systembolaget alkohol prisvärd", "Systembolaget alkohol billig", "Systembolaget alkohol bäst", 
    "Systembolaget alkohol hög APK", "Systembolaget alkohol mest prisvärd", "Systembolaget alkohol billigast", 
    "Systembolaget alkohol bäst", "Systembolaget alkohol hög APK", "mest alkohol för pengarna Systembolaget", 
    "mest prisvärd alkohol Systembolaget", "billigaste alkohol Systembolaget", "bästa alkohol Systembolaget", 
    "hög APK Systembolaget", "mest prisvärd alkohol per krona Systembolaget", 
    "billigaste alkohol per krona Systembolaget", "bästa alkohol per krona Systembolaget", 
    "hög APK per krona Systembolaget", "Systembolaget bästa köp", "Systembolaget billigaste alkohol", 
    "Systembolaget hög APK", "Systembolaget mest prisvärd", "Systembolaget alkohol ranking", 
    "Systembolaget alkohol prisvärd", "Systembolaget alkohol billig", "Systembolaget alkohol bäst", 
    "Systembolaget alkohol hög APK", "Systembolaget alkohol mest prisvärd", "Systembolaget alkohol billigast", 
    "Systembolaget alkohol bäst", "Systembolaget alkohol hög APK", "mest alkohol för pengarna Systembolaget", 
    "mest prisvärd alkohol Systembolaget", "billigaste alkohol Systembolaget", "bästa alkohol Systembolaget", 
    "hög APK Systembolaget", "mest prisvärd alkohol per krona Systembolaget", 
    "billigaste alkohol per krona Systembolaget", "bästa alkohol per krona Systembolaget", 
    "hög APK per krona Systembolaget", "Systembolaget bästa köp", "Systembolaget billigaste alkohol", 
    "Systembolaget hög APK", "Systembolaget mest prisvärd", "Systembolaget alkohol ranking", 
    "Systembolaget alkohol prisvärd", "Systembolaget alkohol billig", "Systembolaget alkohol bäst", 
    "Systembolaget alkohol hög APK", "Systembolaget alkohol mest prisvärd", "Systembolaget alkohol billigast", 
    "Systembolaget alkohol bäst", "Systembolaget alkohol hög APK", "mest alkohol för pengarna Systembolaget", 
    "mest prisvärd alkohol Systembolaget", "billigaste alkohol Systembolaget", "bästa alkohol Systembolaget", 
    "hög APK Systembolaget", "mest prisvärd alkohol per krona Systembolaget", 
    "billigaste alkohol per krona Systembolaget", "bästa alkohol per krona Systembolaget", 
    "hög APK per krona Systembolaget", "Systembolaget bästa köp", "Systembolaget billigaste alkohol", 
    "Systembolaget hög APK", "Systembolaget mest prisvärd", "Systembolaget alkohol ranking", 
    "Systembolaget alkohol prisvärd", "Systembolaget alkohol billig", "Systembolaget alkohol bäst", 
    "Systembolaget alkohol hög APK", "Systembolaget alkohol mest prisvärd", "Systembolaget alkohol billigast", 
    "Systembolaget alkohol bäst", "Systembolaget alkohol hög APK", "mest alkohol för pengarna Systembolaget", 
    "mest prisvärd alkohol Systembolaget", "billigaste alkohol Systembolaget", "bästa alkohol Systembolaget", 
    "hög APK Systembolaget", "mest prisvärd alkohol per krona Systembolaget", 
    "billigaste alkohol per krona Systembolaget", "bästa alkohol per krona Systembolaget", 
    "hög APK per krona Systembolaget", "Systembolaget bästa köp", "Systembolaget billigaste alkohol", 
    "Systembolaget hög APK", "Systembolaget mest prisvärd", "Systembolaget alkohol ranking", 
    "Systembolaget alkohol prisvärd", "Systembolaget alkohol billig", "Systembolaget alkohol bäst", 
    "Systembolaget alkohol hög APK", "Systembolaget alkohol mest prisvärd", "Systembolaget alkohol billigast", 
    "Systembolaget alkohol bäst", "Systembolaget alkohol hög APK", "mest alkohol för pengarna Systembolaget", 
    "mest prisvärd alkohol Systembolaget", "billigaste alkohol Systembolaget", "bästa alkohol Systembolaget", 
    "hög APK Systembolaget", "mest prisvärd alkohol per krona Systembolaget", 
    "billigaste alkohol per krona Systembolaget", "bästa alkohol per krona Systembolaget", 
    "hög APK per krona Systembolaget", "Systembolaget bästa köp", "Systembolaget billigaste alkohol", 
    "Systembolaget hög APK", "Systembolaget mest prisvärd", "Systembolaget alkohol ranking", 
    "Systembolaget alkohol prisvärd", "Systembolaget alkohol billig", "Systembolaget alkohol bäst", 
    "Systembolaget alkohol hög APK", "Systembolaget alkohol mest prisvärd", "Systembolaget alkohol billigast", 
    "Systembolaget alkohol bäst", "Systembolaget alkohol hög APK", "mest alkohol för pengarna Systembolaget", 
    "mest prisvärd alkohol Systembolaget", "billigaste alkohol Systembolaget", "bästa alkohol Systembolaget", 
    "hög APK Systembolaget", "mest prisvärd alkohol per krona Systembolaget", 
    "billigaste alkohol per krona Systembolaget", "bästa alkohol per krona Systembolaget", 
    "hög APK per krona Systembolaget", "Systembolaget bästa köp", "Systembolaget billigaste alkohol", 
    "Systembolaget hög APK", "Systembolaget mest prisvärd", "Systembolaget alkohol ranking", 
    "Systembolaget alkohol prisvärd", "Systembolaget alkohol billig", "Systembolaget alkohol bäst", 
    "Systembolaget alkohol hög APK", "Systembolaget alkohol mest prisvärd", "Systembolaget alkohol billigast", 
    "Systembolaget alkohol bäst", "Systembolaget alkohol hög APK", "mest alkohol för pengarna Systembolaget", 
    "mest prisvärd alkohol Systembolaget", "billigaste alkohol Systembolaget", "bästa alkohol Systembolaget", 
    "hög APK Systembolaget", "mest prisvärd alkohol per krona Systembolaget", 
    "billigaste alkohol per krona Systembolaget", "bästa alkohol per krona Systembolaget", 
    "hög APK per krona Systembolaget", "Systembolaget bästa köp", "Systembolaget billigaste alkohol", 
    "Systembolaget hög APK", "Systembolaget mest prisvärd", "Systembolaget alkohol ranking", 
    "Systembolaget alkohol prisvärd", "Systembolaget alkohol billig", "Systembolaget alkohol bäst", 
    "Systembolaget alkohol hög APK", "Systembolaget alkohol mest prisvärd", "Systembolaget alkohol billigast", 
    "Systembolaget alkohol bäst", "Systembolaget alkohol hög APK", "mest alkohol för pengarna Systembolaget", 
    "mest prisvärd alkohol Systembolaget", "billigaste alkohol Systembolaget", "bästa alkohol Systembolaget", 
    "hög APK Systembolaget", "mest prisvärd alkohol per krona Systembolaget", 
    "billigaste alkohol per krona Systembolaget", "bästa alkohol per krona Systembolaget", 
    "hög APK per krona Systembolaget", "Systembolaget bästa köp", "Systembolaget billigaste alkohol", 
    "Systembolaget hög APK", "Systembolaget mest prisvärd", "Systembolaget alkohol ranking", 
    "Systembolaget alkohol prisvärd", "Systembolaget alkohol billig", "Systembolaget alkohol bäst", 
    "Systembolaget alkohol hög APK", "Systembolaget alkohol mest prisvärd", "Systembolaget alkohol billigast", 
    "Systembolaget alkohol bäst", "Systembolaget alkohol hög APK", "mest alkohol för pengarna Systembolaget", 
    "mest prisvärd alkohol Systembolaget", "billigaste alkohol Systembolaget", "bästa alkohol Systembolaget", 
    "hög APK Systembolaget", "mest prisvärd alkohol per krona Systembolaget", 
    "billigaste alkohol per krona Systembolaget", "bästa alkohol per krona Systembolaget", 
    "hög APK per krona Systembolaget", "Systembolaget bästa köp", "Systembolaget billigaste alkohol", 
    "Systembolaget hög APK", "Systembolaget mest prisvärd", "Systembolaget alkohol ranking", 
    "Systembolaget alkohol prisvärd", "Systembolaget alkohol billig", "Systembolaget alkohol bäst", 
    "Systembolaget alkohol hög APK", "Systembolaget alkohol mest prisvärd", "Systembolaget alkohol billigast", 
    "Systembolaget alkohol bäst", "Systembolaget alkohol hög APK", "mest alkohol för pengarna Systembolaget", 
    "mest prisvärd alkohol Systembolaget", "billigaste alkohol Systembolaget", "bästa alkohol Systembolaget", 
    "hög APK Systembolaget", "mest prisvärd alkohol per krona Systembolaget", 
    "billigaste alkohol per krona Systembolaget", "bästa alkohol per krona Systembolaget", 
    "hög APK per krona Systembolaget", "Systembolaget bästa köp", "Systembolaget billigaste alkohol", 
    "Systembolaget hög APK", "Systembolaget mest prisvärd", "Systembolaget alkohol ranking", 
    "Systembolaget alkohol prisvärd", "Systembolaget alkohol billig", "Systembolaget alkohol bäst", 
    "Systembolaget alkohol hög APK", "Systembolaget alkohol mest prisvärd", "Systembolaget alkohol billigast", 
    "Systembolaget alkohol bäst", "Systembolaget alkohol hög APK", "mest alkohol för pengarna Systembolaget", 
    "mest prisvärd alkohol Systembolaget", "billigaste alkohol Systembolaget", "bästa alkohol Systembolaget", 
    "hög APK Systembolaget", "mest prisvärd alkohol per krona Systembolaget", 
    "billigaste alkohol per krona Systembolaget", "bästa alkohol per krona Systembolaget", 
    "hög APK per krona Systembolaget", "Systembolaget bästa köp", "Systembolaget billigaste alkohol", 
    "Systembolaget hög APK", "Systembolaget mest prisvärd", "Systembolaget alkohol ranking", 
    "Systembolaget alkohol prisvärd", "Systembolaget alkohol billig", "Systembolaget alkohol bäst", 
    "Systembolaget alkohol hög APK", "Systembolaget alkohol mest prisvärd", "Systembolaget alkohol billigast", 
    "Systembolaget alkohol bäst", "Systembolaget alkohol hög APK", "mest alkohol för pengarna Systembolaget", 
    "mest prisvärd alkohol Systembolaget", "billigaste alkohol Systembolaget", "bästa alkohol Systembolaget", 
    "hög APK Systembolaget", "mest prisvärd alkohol per krona Systembolaget", 
    "billigaste alkohol per krona Systembolaget", "bästa alkohol per krona Systembolaget", 
    "hög APK per krona Systembolaget", "Systembolaget bästa köp", "Systembolaget billigaste alkohol", 
    "Systembolaget hög APK", "Systembolaget mest prisvärd", "Systembolaget alkohol ranking", 
    "Systembolaget alkohol prisvärd", "Systembolaget alkohol billig", "Systembolaget alkohol bäst", 
    "Systembolaget alkohol hög APK", "Systembolaget alkohol mest prisvärd", "Systembolaget alkohol billigast", 
    "Systembolaget alkohol bäst", "Systembolaget alkohol hög APK", "mest alkohol för pengarna Systembolaget", 
    "mest prisvärd alkohol Systembolaget", "billigaste alkohol Systembolaget", "bästa alkohol Systembolaget", 
    "hög APK Systembolaget", "mest prisvärd alkohol per krona Systembolaget", 
    "billigaste alkohol per krona Systembolaget", "bästa alkohol per krona Systembolaget", 
    "hög APK per krona Systembolaget", "Systembolaget bästa köp", "Systembolaget billigaste alkohol", 
    "Systembolaget hög APK", "Systembolaget mest prisvärd", "Systembolaget alkohol ranking", 
    "Systembolaget alkohol prisvärd", "Systembolaget alkohol billig", "Systembolaget alkohol bäst", 
    "Systembolaget alkohol hög APK", "Systembolaget alkohol mest prisvärd", "Systembolaget alkohol billigast", 
    "Systembolaget alkohol bäst", "Systembolaget alkohol hög APK", "mest alkohol för pengarna Systembolaget", 
    "mest prisvärd alkohol Systembolaget", "billigaste alkohol Systembolaget", "bästa alkohol Systembolaget", 
    "hög APK Systembolaget", "mest prisvärd alkohol per krona Systembolaget", 
    "billigaste alkohol per krona Systembolaget", "bästa alkohol per krona Systembolaget", 
    "hög APK per krona Systembolaget", "Systembolaget bästa köp", "Systembolaget billigaste alkohol", 
    "Systembolaget hög APK", "Systembolaget mest prisvärd", "Systembolaget alkohol ranking", 
    "Systembolaget alkohol prisvärd", "Systembolaget alkohol billig", "Systembolaget alkohol bäst", 
    "Systembolaget alkohol hög APK", "Systembolaget alkohol mest prisvärd", "Systembolaget alkohol billigast", 
    "Systembolaget alkohol bäst", "Systembolaget alkohol hög APK", "mest alkohol för pengarna Systembolaget", 
    "mest prisvärd alkohol Systembolaget", "billigaste alkohol Systembolaget", "bästa alkohol Systembolaget", 
    "hög APK Systembolaget", "mest prisvärd alkohol per krona Systembolaget", 
    "billigaste alkohol per krona Systembolaget", "bästa alkohol per krona Systembolaget", 
    "hög APK per krona Systembolaget", "Systembolaget bästa köp", "Systembolaget billigaste alkohol", 
    "Systembolaget hög APK", "Systembolaget mest prisvärd", "Systembolaget alkohol ranking", 
    "Systembolaget alkohol prisvärd", "Systembolaget alkohol billig", "Systembolaget alkohol bäst", 
    "Systembolaget alkohol hög APK", "Systembolaget alkohol mest prisvärd", "Systembolaget alkohol billigast", 
    "Systembolaget alkohol bäst", "Systembolaget alkohol hög APK", "mest alkohol för pengarna Systembolaget", 
    "mest prisvärd alkohol Systembolaget", "billigaste alkohol Systembolaget", "bästa alkohol Systembolaget", 
    "hög APK Systembolaget", "mest prisvärd alkohol per krona Systembolaget", 
    "billigaste alkohol per krona Systembolaget", "bästa alkohol per krona Systembolaget", 
    "hög APK per krona Systembolaget", "Systembolaget bästa köp", "Systembolaget billigaste alkohol",
];

export default seoKeywords;